CREATE TABLE restaurants (
    rid   INT  PRIMARY KEY  AUTO_INCREMENT,
    rName VARCHAR(50) NOT NULL UNIQUE,
    rUsername VARCHAR(50) NOT NULL UNIQUE,
    rPassword VARCHAR(255) NOT NULL,
    rAddress  VARCHAR(255) NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
